# Base16 Tokyo City Dark - wezterm color config
# Scheme by MichaÃ«l Ball
[colors]
background = "#171d23"
foreground = "#d8e2ec"

cursor_bg = "#d8e2ec"
cursor_border = "#d8e2ec"
cursor_fg = "#171d23"

selection_bg = "#d8e2ec"
selection_fg = "#171d23"

ansi = [
  "#171d23",
  "#f7768e",
  "#9ece6a",
  "#b7c5d3",
  "#7aa2f7",
  "#bb9af7",
  "#89ddff",
  "#f6f6f8"
  ]
brights = [
  "#526270",
  "#f7768e",
  "#9ece6a",
  "#b7c5d3",
  "#7aa2f7",
  "#bb9af7",
  "#89ddff",
  "#fbfbfd"
  ]

[colors.indexed]
16 = "#ff9e64"
17 = "#bb9af7"
18 = "#1d252c"
19 = "#28323a"
20 = "#b7c5d3"
21 = "#d8e2ec"
