# Scheme system: base16
# Scheme name: Horizon Light (legacy)
# Scheme author: MichaÃ«l Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xfdf0ed'
foreground = '0x403c3d'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xfdf0ed'
cursor = '0x403c3d'

# Normal colors
[colors.normal]
black = '0xfadad1'
red = '0xf7939b'
green = '0x94e1b0'
yellow = '0xfbe0d9'
blue = '0xda103f'
magenta = '0x1d8991'
cyan = '0xdc3318'
white = '0x302c2d'

# Bright colors
[colors.bright]
black = '0xf9cbbe'
red = '0xf6661e'
green = '0xfadad1'
yellow = '0xf9cbbe'
blue = '0x948c8a'
magenta = '0x302c2d'
cyan = '0xe58c92'
white = '0x201c1d'
