# Scheme system: base16
# Scheme name: Tokyo Night Terminal Light (legacy)
# Scheme author: MichaÃ«l Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xd5d6db'
foreground = '0x4c505e'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xd5d6db'
cursor = '0x4c505e'

# Normal colors
[colors.normal]
black = '0xcbccd1'
red = '0x8c4351'
green = '0x33635c'
yellow = '0x8f5e15'
blue = '0x34548a'
magenta = '0x5a4a78'
cyan = '0x0f4b6e'
white = '0x1a1b26'

# Bright colors
[colors.bright]
black = '0xdfe0e5'
red = '0x965027'
green = '0xcbccd1'
yellow = '0xdfe0e5'
blue = '0x4c505e'
magenta = '0x1a1b26'
cyan = '0x655259'
white = '0x1a1b26'
