# Rio Terminal Theme
# Scheme system: base16
# Scheme name: Brewer (legacy)
# Scheme author: Timoth√©e Poisot (http://github.com/tpoisot)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

[colors]
selection-background = '#515253' # base02
selection-foreground = '#b7b8b9' # base05

cursor         = '#b7b8b9' # base05
tabs           = '#2e2f30' # base01
tabs-active    = '#515253' # base02

background     = '#0c0d0e' # base00
foreground     = '#b7b8b9' # base05
black          = '#2e2f30' # base01
red            = '#e31a1c' # base08
yellow         = '#dca060' # base0A
green          = '#31a354' # base0B
cyan           = '#80b1d3' # base0C
blue           = '#3182bd' # base0D
magenta        = '#756bb1' # base0E
white          = '#dadbdc' # base06

dim-foreground   = '#b7b8b9' # base05
dim-black        = '#2e2f30' # base01
dim-red          = '#e31a1c' # base08
dim-yellow       = '#dca060' # base0A
dim-green        = '#31a354' # base0B
dim-cyan         = '#80b1d3' # base0C
dim-blue         = '#3182bd' # base0D
dim-magenta      = '#756bb1' # base0E
dim-white        = '#959697' # base04

light-foreground = '#b7b8b9' # base05
light-black      = '#515253' # base02
light-red        = '#e6550d' # base09
light-yellow     = '#515253' # base02
light-green      = '#2e2f30' # base01
light-cyan       = '#b15928' # base0F
light-blue       = '#959697' # base04
light-magenta    = '#dadbdc' # base06
light-white      = '#fcfdfe' # base07
