# Rio Terminal Theme
# Scheme system: base16
# Scheme name: Tokyo City Light (legacy)
# Scheme author: MichaÃ«l Ball
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-terminal)

[colors]
selection-background = '#edeff6' # base02
selection-foreground = '#343b59' # base05

cursor         = '#343b59' # base05
tabs           = '#f6f6f8' # base01
tabs-active    = '#edeff6' # base02

background     = '#fbfbfd' # base00
foreground     = '#343b59' # base05
black          = '#f6f6f8' # base01
red            = '#8c4351' # base08
yellow         = '#4c505e' # base0A
green          = '#485e30' # base0B
cyan           = '#4c505e' # base0C
blue           = '#34548a' # base0D
magenta        = '#5a4a78' # base0E
white          = '#1d252c' # base06

dim-foreground   = '#343b59' # base05
dim-black        = '#f6f6f8' # base01
dim-red          = '#8c4351' # base08
dim-yellow       = '#4c505e' # base0A
dim-green        = '#485e30' # base0B
dim-cyan         = '#4c505e' # base0C
dim-blue         = '#34548a' # base0D
dim-magenta      = '#5a4a78' # base0E
dim-white        = '#4c505e' # base04

light-foreground = '#343b59' # base05
light-black      = '#edeff6' # base02
light-red        = '#965027' # base09
light-yellow     = '#edeff6' # base02
light-green      = '#f6f6f8' # base01
light-cyan       = '#5a4a78' # base0F
light-blue       = '#4c505e' # base04
light-magenta    = '#1d252c' # base06
light-white      = '#171d23' # base07
